### ISSUE TITLE
iOS 13 not working

### ISSUE THREAD

**Issue by schenkty** [chrs1885/SheetyColors#3] opened 2019-07-20 17:44 UTC
## What did you do?
I was testing my app on iOS 13 beta 4

## What did you expect to happen?
I expected it work as it does on iOS 12

## What happened instead?
The color section and sliders were all gray

**Comment by chrs1885** [comment] 2019-07-21 18:20
Hi @schenkty, I haven‘t had the chance to to look into this, yet. But I will try to add iOS 13 support asap. I‘ll keep you in the loop once I‘ve figured out what the issue is. Are you planning to ship an app that is using the lib?

**Comment by schenkty** [comment] 2019-07-21 18:24
@chrs1885 Yes, the app currently has the lib implemented and is working for iOS 12.

**Comment by chrs1885** [comment] 2019-07-21 18:26
What‘s the name of the app? Is it available on the App Store? Cheers!

**Comment by schenkty** [comment] 2019-07-21 18:34
@chrs1885 not available yet but the app name is called Linkz

**Comment by chrs1885** [comment] 2019-07-24 20:28
@schenkty Unfortunately, there doesn‘t seem to be a fix for that right now. However, I‘m pretty sure that this issue will be addressed in the upcoming beta releases. Otherwise, I‘m gonna wrap the color picker inside a custom action sheet controller. Any thoughts on that?

**Comment by schenkty** [comment] 2019-07-24 20:39
What is the issue for it not working? It would probably work fine inside a custom action sheet controller if it has to be in one. I have had issues with other frameworks that use customer action sheet controllers where it doesn't work properly on iPads.

**Comment by chrs1885** [comment] 2019-07-24 21:11
Exactly. The main reason why I initially decided to go with Apple‘s controller class was to guarantee an expected look&feel/behaviour for all iOS versions. Let‘s give it another beta or two to see if this gets fixed. It seems like that all views inside the action sheet besides the button are simply cut out 😔

**Comment by schenkty** [comment] 2019-07-24 21:13
Can you report the issue to Apple? Maybe they can fix it or suggest the best option moving forward.

**Comment by chrs1885** [comment] 2019-07-24 21:17
Well, the documentation says that the alert controller is not ment to be customized. Maybe this is on purpose. There seems to be a guy having the same issue: https://stackoverflow.com/questions/56955800/ios13-uialertcontroller-with-custom-view-preferredstyle-as-actionsheet-graysca

**Comment by chrs1885** [comment] 2019-07-24 21:21
Presenting the picker inside an alert instead of an action sheet might be a workaround for now.

**Comment by schenkty** [comment] 2019-07-24 21:22
If the same functionality can be done with a custom controller. that may be the best option. I wouldn't suggest doing a hot fix to just have to fix it again with another iOS change.

**Comment by chrs1885** [comment] 2019-07-24 21:27
I‘m gonna install iOS 13 on one of my testing devices to see if the music app (which also seems to have custom action sheets) can handle the issue properly. If so, I will start to work on a custom controller that immitates the look and feel 😉

**Comment by schenkty** [comment] 2019-07-24 21:52
Sounds great! Thank you for the commitment to this repo, it’s truly awesome.

**Comment by chrs1885** [comment] 2019-07-30 20:53
@schenkty Good news. I've managed to get it working on iOS 13. I'm going to publish a new version in the upcoming days.

<img width="410" alt="Bildschirmfoto 2019-07-30 um 22 53 05" src="https://user-images.githubusercontent.com/1390908/62164533-df667200-b31c-11e9-9f4e-64780af1e44d.png">

**Comment by schenkty** [comment] 2019-07-30 20:58
That is awesome, congratulations! Does it work the same way as before? How does it work on iPad?

**Comment by chrs1885** [comment] 2019-07-31 18:05
It pretty much works the same way as before. Still, the view is based on `UIAlterViewController`. Didn't check the behavior on an iPad, though.

**Comment by chrs1885** [comment] 2019-07-31 18:49
@schenkty This has been added to the develop branch already and is going to be part of the upcoming 1.0.0 release. Feel free to star this repo in case you are happy with it =)

**Closed as completed by chrs1885** 2019-07-31 18:49 UTC

**Comment by chrs1885** [comment] 2019-08-07 21:30
@schenkty v 1.0.0 is available. Please let me know, what you are thinking!
